version: "3.9"

services:
  mysql:
    image: mysql:8.0

    container_name: hotel-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: hotel_booking
      MYSQL_USER: admin
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: